"""Acceptance tests for the Phase-3 authority classifier and its error propagation.

Kept moderate in size for speed. Locks the honest findings: text-based attacks are
resisted, perfect metadata forgeries are not (by construction), and per-document
accuracy does not guarantee end-to-end correctness.
"""

from __future__ import annotations

from pathlib import Path

from cfna.authority_data import gen_examples, gen_resolution_trials
from cfna.authority_eval import load_blind, train_and_evaluate

_RES = train_and_evaluate(seed=0, n_train=2500, n_test=600, n_trials=300, blind_path=None)


def test_data_generator_deterministic():
    assert [repr(d) for d in gen_examples(1, 60)] == [repr(d) for d in gen_examples(1, 60)]
    assert gen_examples(2, 60) != gen_examples(1, 60)


def test_classifier_is_accurate_and_calibrated():
    ho = _RES["held_out"]
    assert ho["accuracy"] > 0.90
    assert ho["false_rejection_rate"] < 0.10
    assert ho["ece"] < 0.10


def test_text_based_attacks_are_resisted():
    acc = _RES["held_out"]["acceptance_by_family"]
    for fam in ("impersonation", "laundering", "paraphrased_official",
                "metadata_text_conflict", "spoof_crude", "spoof_medium"):
        assert acc.get(fam, 0.0) == 0.0, (fam, acc.get(fam))


def test_training_excludes_feature_identical_forgeries():
    # Perfect forgeries are unlearnable label noise; they must not be in training data.
    # They are handled by the cryptographic provenance gate, not the classifier.
    fams = {d.family for d in gen_examples(0, 900)}
    assert "spoof_perfect" not in fams


def test_error_propagates_but_stays_bounded():
    ep = _RES["error_propagation"]
    assert ep["oracle_accuracy"] == 1.0
    assert ep["predicted_accuracy"] < ep["oracle_accuracy"]   # learning has a cost
    assert ep["predicted_accuracy"] > 0.6                     # but the system still works
    assert ep["predicted_poison_rate"] >= ep["oracle_poison_rate"]


def test_blind_set_present_and_valid():
    p = Path("data/authority_blind.jsonl")
    if not p.exists():
        return  # generated by a separate process; skip if absent
    docs = load_blind(str(p))
    assert len(docs) >= 100
    from cfna.authority_data import CHANNELS
    for d in docs:
        assert d.channel in CHANNELS
        assert d.label_trusted == (d.label_authority not in
                                   {"unverified_external_content", "generated_hypothesis",
                                    "model_inference"})
