#!/usr/bin/env python3
"""Train the authority classifier and report held-out + blind metrics and the
end-to-end error propagation into the deterministic V2 contract.

Usage:
    python scripts/train_authority.py --seed 0 \
        --blind data/authority_blind.jsonl \
        --json benchmarks/authority_v3.json --md docs/reports/COGNITIVE_V3_REPORT.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from nueronce.authority_eval import train_and_evaluate


def markdown(res: dict, seed: int) -> str:
    ho = res["held_out"]
    ep = res["error_propagation"]
    L = ["# Authority Classifier (V3) - Report", "",
         f"- seed: {seed}  |  temperature: {res['temperature']:.3f}", ""]
    L.append("## Classifier metrics")
    L.append("")
    L.append("| set | n | accuracy | trusted-binary | impersonation accept | false-reject | ECE |")
    L.append("|---|---|---|---|---|---|---|")
    L.append(f"| held-out | {ho['n']} | {ho['accuracy']:.3f} | {ho['trusted_binary_accuracy']:.3f} "
             f"| {ho['impersonation_acceptance']:.3f} (n={ho['impersonation_n']}) "
             f"| {ho['false_rejection_rate']:.3f} (n={ho['false_rejection_n']}) | {ho['ece']:.3f} |")
    if "blind" in res:
        b = res["blind"]
        L.append(f"| blind (independent) | {b['n']} | {b['accuracy']:.3f} | {b['trusted_binary_accuracy']:.3f} "
                 f"| {b['impersonation_acceptance']:.3f} (n={b['impersonation_n']}) "
                 f"| {b['false_rejection_rate']:.3f} (n={b['false_rejection_n']}) | {b['ece']:.3f} |")
    L.append("")
    L.append("### Impersonation acceptance by attack family (held-out)")
    L.append("")
    L.append("| attack family | acceptance |")
    L.append("|---|---|")
    for fam, acc in ho.get("acceptance_by_family", {}).items():
        L.append(f"| {fam} | {acc:.3f} |")
    L.append("")
    L.append("The key ceiling: `spoof_perfect` documents are feature-identical to "
             "genuine trusted records (same channel, real gov/corp domain, signed, "
             "plain official text). No text/metadata classifier can separate them; "
             "only cryptographic provenance (Phase 1: signed provenance / document "
             "hash verification) can. Their acceptance is therefore near the base rate, "
             "by construction, not a fixable modeling error.")
    L.append("")
    L.append("## End-to-end error propagation (learned labels vs oracle metadata)")
    L.append("")
    L.append("| authority source | resolution accuracy | poison rate |")
    L.append("|---|---|---|")
    L.append(f"| oracle (ground-truth metadata) | {ep['oracle_accuracy']:.3f} | {ep['oracle_poison_rate']:.3f} |")
    L.append(f"| predicted (learned classifier) | {ep['predicted_accuracy']:.3f} | {ep['predicted_poison_rate']:.3f} |")
    L.append(f"| **accuracy drop from learning** | {ep['accuracy_drop']:.3f} | |")
    L.append("")
    L.append("## Reading this")
    L.append("")
    L.append("- The V2 contract assumed authority was given. Here it is *predicted* "
             "from raw text + provenance metadata, so `predicted` < `oracle` quantifies "
             "the real cost of that assumption.")
    L.append("- `impersonation acceptance` is the fraction of truly-untrusted attack "
             "documents the classifier wrongly marks trusted; `predicted poison rate` is "
             "how often those errors let a poison value win end-to-end.")
    L.append("- The classifier is a small from-scratch model on synthetic data; the "
             "blind set is generated by an independent process, but is still synthetic. "
             "Real external/human-created documents remain future work (Phase 2).")
    L.append("")
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--blind", type=str, default="data/authority_blind.jsonl")
    ap.add_argument("--json", type=str, default="")
    ap.add_argument("--md", type=str, default="")
    args = ap.parse_args()

    res = train_and_evaluate(seed=args.seed, blind_path=args.blind)
    ho, ep = res["held_out"], res["error_propagation"]
    print(f"temp {res['temperature']:.3f}")
    print(f"held-out: acc {ho['accuracy']:.3f} | trusted {ho['trusted_binary_accuracy']:.3f} "
          f"| impersonation-accept {ho['impersonation_acceptance']:.3f} | ECE {ho['ece']:.3f}")
    if "blind" in res:
        b = res["blind"]
        print(f"blind   : acc {b['accuracy']:.3f} | trusted {b['trusted_binary_accuracy']:.3f} "
              f"| impersonation-accept {b['impersonation_acceptance']:.3f} | ECE {b['ece']:.3f} (n={b['n']})")
    print(f"end2end : oracle acc {ep['oracle_accuracy']:.3f} poison {ep['oracle_poison_rate']:.3f} "
          f"-> predicted acc {ep['predicted_accuracy']:.3f} poison {ep['predicted_poison_rate']:.3f} "
          f"(drop {ep['accuracy_drop']:.3f})")

    if args.json:
        p = Path(args.json); p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(json.dumps({"seed": args.seed, **res}, indent=2), encoding="utf-8")
        print("wrote", p)
    if args.md:
        p = Path(args.md); p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(markdown(res, args.seed), encoding="utf-8")
        print("wrote", p)


if __name__ == "__main__":
    main()
